### ISSUE TITLE
Third party mail clients

### ISSUE THREAD

**Issue by musikundberge** [holtwick/pdfify#32]
Dropping mails from Apple Mail works fine.

What about third party mail clients like Spark?

Kind regards from Germany

**Comment by holtwick** [comment]
Thanks for opening the ticket. Did you try it with Spark? Did you get an error message?

Usually most clients that support the `eml` format work with PDFify. Postbox does not AFAIK.

**Comment by musikundberge** [comment]
I tried to drop a simple mail to the dock icon - nothing happened (no green + sign)

**Comment by holtwick** [comment]
Spark will not be supported, it only offers internal data when dragging. Export is also limited to certain apps. Readdle seem to be the gatekeeper: https://sparkmailapp.com/help/191-connect-other-productivity-apps-to-spark.html 

Alternative: Use the print dialog and export as PDF from there.

![image](https://user-images.githubusercontent.com/49557/94052079-bf272b80-fdd8-11ea-9f6b-0dddf5ecf765.png)

**Comment by musikundberge** [comment]
Ok - thanks a lot 😀

**Comment by holtwick** [comment]
Clarified in help https://pdfify.app/help#mails
