### ISSUE TITLE
Provide some information when a scan fails

### ISSUE THREAD

**Issue by acrostich** [holtwick/pdfify#39]
When the scan returns an error, inform the user that the scan couldn't complete instead of just not creating a page.

I assume you are using the macOS scanning engine. I use a Samsung M2885FW scanner. Using Preview scanning works fine in Text or B&W, but in colour it fails with this error message: 

<img width="532" alt="Screenshot 2020-09-23 at 20 39 24" src="https://user-images.githubusercontent.com/1878811/94061230-04e5f300-fddd-11ea-8727-99724402ee2a.png">

So when using this engine programmatically it is likely you get some error code which appears to be ignored.

I suggest you provide some information along the lines of 'macOS has failed to to scan your document'. Something that a) makes it clear to the user that there has a been an issue, and b) makes it clear that the issue is in the macOS driver and not your app.

The alternative of providing your scanning engine that works with more scanners would be even better, but that's a huge job and likely too much work to support for the value it brings.

FYI When scanning in colour with that scanner, Prizmo fails by closing the app while PDFScanner succeeds in scanning colour documents. (I hope it'll work better in future versions of macOS and it does seem that HP has now started supporting the Samsung devices since its purchase of that part of Samsung)

**Comment by holtwick** [comment]
Scanner feedback as dialogs comes directly from macOS. The more detailed info is dumped in the log files. In the support dialog the log files can be seen and send.
