### ISSUE TITLE
Batch Processing / Automation ideas for 3.4

### ISSUE THREAD

**Issue by ubiquit-y** [holtwick/pdfify#43]
**Is your feature request related to a problem? Please describe.**

PDF documents received external contain often only images or only partly OCR layer or non at all.  A solution to OCR these PDF Files in a batch mode or multiple at one time without opening and clicking every single document. 

**Describe the solution you'd like**

 Another simple solution is a batch processing dialog similar to Kofax, that opens from a "OCR Files" menu and presents an area to drag multiple files, has a add / remove / start functions and visualizes the process of every file and potential errors.

**Describe alternatives you've considered**

Simple solution would also be dragging multiple files onto the PDFify icon but a similar window as mentioned above would be needed to indicate process and display errors.

**Additional context**

**Comment by holtwick** [comment]
I'm going to add more automation features. By now this is available to process multiple files via Finder at once https://pdfify.app/help#batch
