### ISSUE TITLE
Family License

### ISSUE THREAD

**Issue by holtwick** [holtwick/pdfify#51]
In-App purchases cannot be shared in a family! That's not ok.

https://support.apple.com/en-us/HT203046

> What you can't share
>     Individual or student Apple Music subscriptions and other third-party subscriptions.
>     In-app purchases.
>     Items that are no longer available on the App Store and iTunes Store.
>     Items that you or another member of your family group have hidden. Learn more about hidden purchases.
>     Some apps from the App Store. Find out if your app is shareable.

Solution: Implement different ways to distribute the app. 

---
Internal reference to original message https://1b.replies.io/#182916/threads/1229595

**Comment by holtwick** [comment]
Fixed in Big Sur? https://9to5mac.com/2020/06/22/apple-adds-developer-option-to-share-in-app-purchases-and-subscriptions-via-family-sharing/

**Comment by stmh** [comment]
I am adding my 2 cents. VPP (Apples volume purchasing program) does also not support subscriptions, which makes it impossible for us to buy licenses for our company. A dedicated Pdfiy Pro which costs 25 EUR would be highly appreciated.

**Comment by holtwick** [comment]
This is fixed in Big Sur now: https://support.apple.com/guide/mac-help/share-purchases-with-your-family-mchlc2b37692/mac

A purchase option outside the AppStore will be added 2021
