### ISSUE TITLE
OCR Batch function

### ISSUE THREAD

**Issue by Madd33n** [holtwick/pdfify#60]
Hi,

i got a lot of PDFs generated over the years. The current option to drag and drop file by file isn't a solution. 
I'm willing to pay for a pro version - but batch processing is a must have for me. 

If you plan to implement it, please just make a simple conversion function (pdf to searchable pdf) without extra saving or other things that disturb a simple batch workflow. Just like a .wav to .mp3 converter.

User can drag and drop as much files as he want in window - press a "start" button - and all the work is done automatically.
In the first versions a "save where the origin file is" option is quite as enough. And please just by overwriting. I dont want to set up 3487 file names or folders.
For me it's essential that I dont need to make specific settings to all those files. Just ocr and add the text layer - overwriting the original file - Done :)

Later you can provide an option to save converted files to a divergent folder or maybe different PDF formats like PDF/A. 

Batch processing should be a "pro" only feature - pretty sure that a lot of people willing to buy it. 

Greetings from Bonn :) If you got any further questions maybe we can discuss it in german - much easier :)
Have a nice day /weekend. 

App Version Info:
de.holtwick.mac.PDFify@3.3.1+116 C3ZTKGP5QS6EQB813CAS165NE8

**Comment by holtwick** [comment]
Hi @Madd33n 

Thanks for your ticket. Indeed, I am planning to add this feature. I assigned it to the next milestone.

Liebe Grüße nach Bonn :)

**Comment by guuuf** [comment]
With these words I bought the PRO version. I hope this feature will be available soon. Greetings from the Ruhrgebiet.

**Comment by hubbeldihub** [comment]
I'm also looking for a batch conversion for my non-PDF/a docs. Pdfify looks great and would be nice if this feature would arrive soon. Any updates on that maybe? (ich will ja nicht drängeln, aber ... 😁) 

See also the users comments at cachys blog, looks like there's no user-friendly alternative for batch & pdfify available at the moment: https://stadt-bremerhaven.de/pdfify-kostenloses-macos-tool-wandelt-in-durchsuchbare-pdf-dateien-um/

**Comment by 0bscur3** [comment]
I also bought the PRO version and getting a batch function will immensely reduce the time needed to OCR the documents that I already have collected over the years. Really looking forward to see this feature soon.

**Comment by svenwiegand** [comment]
I am looking exactly for this and I go a step further: I don‘t want a UI at all, but only a siri shortcut action which allows me to feed in a scanned PDF and get out a searchable PDF. 

Currently I‘m using Abby FineReader‘s automator action, but I really would like to switch to macOS 12‘s shortcuts s they are so much cooler. Unfortunately currently there doesn’t seem to exist and app providing this feature.

**Comment by mat1696** [comment]
> Hi @Madd33n
> 
> Thanks for your ticket. Indeed, I am planning to add this feature. I assigned it to the next milestone.
> 
> Liebe Grüße nach Bonn :)

I contacted you via email for such a request. So have you any ETA? That's a MUST HAVE as well for me, so I cannot pay for the app since it's not implemented... and that's a shame, because otherwise your app is really great!

**Comment by holtwick** [comment]
This is now available through Finder Extensions. See beta https://pdfify.app/de/help#beta Will be release next days. See also https://github.com/holtwick/pdfify/issues/74#issuecomment-1074885866
