### ISSUE TITLE
Screenshot always copies desktop

### ISSUE THREAD

**Issue by Astelix** [holtwick/pdfify#62]
Screenshot never copies the selected Textframe but always the desktop picture behind the Textwindow.

When I copy this:

![image](https://user-images.githubusercontent.com/10071571/101019995-17637200-356e-11eb-897d-91d887351860.png)

pdffify receives this

![Bildschirmfoto 2020-12-03 um 13 49 03](https://user-images.githubusercontent.com/10071571/101020169-5e516780-356e-11eb-83a1-506a598029c7.png)

App Version Info:
de.holtwick.mac.PDFify@3.3.1+116 68W7BQB4SH0HQF69DS82AY8S5W

**Comment by holtwick** [comment]
![20220308-115323-capture-holtwick@2x](https://user-images.githubusercontent.com/49557/157224609-2195ac39-dfd1-4639-8890-db9bfe50b2cf.png)

It is required to allow the app to record screen content.
