### ISSUE TITLE
Automatic page correction

### ISSUE THREAD

**Issue by BioExorzist** [holtwick/pdfify#65]
Please explain your idea to make the app better:
That the scanner detects if a document has been scanned the wrong way and then automatically rotates the page correctly. Possibly also with minimal rotations of 1-2 percent.

App Version Info:
de.holtwick.mac.PDFify@3.3.2+130 0ABA9TA42H6NK6BPKVTZDX8Y9R

**Comment by holtwick** [comment]
See also #28

**Comment by holtwick** [comment]
Duplicate of https://github.com/holtwick/pdfify/issues/28
