### ISSUE TITLE
Abbruch bei mehrseitigen Dokumenten

### ISSUE THREAD

**Issue by Baerlauch88** [holtwick/pdfify#68]
Please describe how the error can be reproduced:

App Version Info:
de.holtwick.mac.PDFify@3.3.2+130 KW537DE3X96VZ4NT8MXSG1J6N8

Mac mini 2020 OSX Big Sur iPhone 12 Pro Max

Bei mehrseitigen Dokumenten wird die Verbindung ohne Kommentar getrennt und alle bereits gescannten Seiten gehen verloren.

**Comment by holtwick** [comment]
Könntest du das in der aktuellen Beta nochmal testen? Sollte nun behoben sein: https://pdfify.app/help#beta
