### ISSUE TITLE
Adjust windows vertically

### ISSUE THREAD

**Issue by gitarzanand** [holtwick/pdfify#78]
Please explain your idea to make the app better:

Have the window be adjustable vertically in addition to horizontally. In order to see the progress of OCR, I have to shrink my dock much smaller than I'd like, and then once I've seen the OCR progress on the bottom right, I have to change my dock back every time. I'd rather just be able to shrink PDFify vertically (as it can already be shrunk horizontally) and have it stay that size.

App Version Info:
de.holtwick.mac.homebrew.PDFify@3.4+154 ZBVB5TNTEX7M9B7E367KDE2Y00

**Comment by holtwick** [comment]
Fixed in beta https://pdfify.app/de/help#beta
