### ISSUE TITLE
Unendliches Lizenz Menü 

### ISSUE THREAD

**Issue by ChristianHaake** [holtwick/pdfify#83]
Please describe how the error can be reproduced:

Moin! 

gerade die Lizenz hinzugefügt und wenn ich im Menü auf PDFify Pro klicke, dann erscheint ein kleiner Bug. Siehe Screen. 

App Version Info:
de.holtwick.mac.homebrew.PDFify@3.6+212 1F56BBB4ND6KS91F8N12KZ3Z6G

<img width="1773" alt="Screenshot 2022-11-12 at 17 09 54" src="https://user-images.githubusercontent.com/48489823/201483313-b36ca5e3-ce01-42b0-a7e8-42a30806226d.png">

**Comment by holtwick** [comment]
Siehe https://github.com/holtwick/pdfify/issues/85#issuecomment-1314055894 Release wahrscheinlich morgen. Danke!
